name: DAST using ZAProxy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Juice Shop container (Test Server)
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
          # ввв
          sleep 60
          # Выводим статус контейнера (для логов)
          docker ps

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          fail_action: false